services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./data:/var/www/html/data
      - ./uploads:/var/www/html/uploads

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025" # SMTP受信用
      - "8025:8025" # ブラウザ確認用（WEB UI）
